name: dumbproxy
summary: Simple, scriptable, secure forward proxy.
description: >
  Simple, scriptable, secure forward proxy. See documentation for details:
  https://github.com/SenseUnit/dumbproxy/blob/master/README.md

confinement: strict
base: core22
adopt-info: dumbproxy

parts:
  dumbproxy:
    plugin: go
    build-snaps: [go/latest/stable]
    build-packages:
      - make
      - git-core
    source: https://github.com/SenseUnit/dumbproxy
    source-type: git
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --always --match=v*.*.* | sed 's/v//')"
    override-build:
      make &&
      cp bin/dumbproxy "$SNAPCRAFT_PART_INSTALL"
    stage:
      - dumbproxy

apps:
  dumbproxy:
    command: dumbproxy
    plugs:
      - network
      - network-bind
